### ISSUE TITLE
Revamp UI and UX

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#115]
There are a number of UI and UX related changes to be made for RS `v2.0`:
- [x] Add dialog popup for keyboard shortcuts when `Shift + ?` are pressed (moved to #226)
- [x] Make all edittexts in template editor use TextInputLayouts (moved to #227)
- [x] Animate stopwatch icon (moved to #230)
  - https://photos.app.goo.gl/Qd1UOS0xL3KNLNY73
  - https://youtu.be/2aq3ljlnQdI
  - https://twitter.com/taylorling/status/989112594161127424
- [x] Make `NewTemplateDialog` a custom view that looks like those [Google chat bubble hints](#chat-bubble-hint) (moved to #229)
- [x] Make all items have the same indent with or without a star visible (moved to #228)
- [x] Make add metric FAB a bottom sheet like in Google Drive
- [x] Add red banner with trash icon in swipe to delete item action like Google apps
- [x] Add no content hint for empty template metric list
- [x] Make checkbox appear on right of text
- [x] Improve performance of stopwatch recyclerview with shared cache pool: https://medium.com/@mgn524/optimizing-nested-recyclerview-a9b7830a4ba7
- [x] Prevent template editor from being scrollable and instead force user to tab on tabs to improve item swipe support
- [x] Fix poor UX when attempting to edit a shared team's template that's inaccessible to the user. We should show a Toast explaining the situation and then finish the template editor activity.
- [x] Fix `AddScoutTemplateSelectorDialog` set as default checkbox not being sticky meaning it scrolls away if there are lots of templates
- [x] Auto scroll to team when selected in tablet mode indirectly e.g. added through FAB
- [x] Fix UI glitches after reordering items by waiting until there's no diff between the two lists
- [x] Prevent settings and template editor from being opened if user is not signed in
- [x] Fix spreadsheet export notification "Share" button not sending broadcast and thus not doing anything.
  - Use a dynamic broadcast receiver from app start
- [x] Add app shortcut to export all teams
- [x] Fix tablet mode edge case where padding is too large when horizontally constrained in team list. **Ha! I spent hours debugging this and it turns out it's [not my fault](https://issuetracker.google.com/issues/64397629).**
- [x] Try to remove various "Are you sure?" dialogs and instead add an undo option
  - `ResetTemplateDialog` **Edit:** since this is a big action like deleting a team, we should add more info and make the warning bigger instead of making it smaller
  - `RemoveAllMetricsDialog`
- [x] Fix day/night color model for selected team items
- [x] Try to animate selecting a team. **Edit:** Turns out it works with `setForeground()`, but it looks ugly weirdly enough.
- [x] Make delete team dialog in scout activity a SnackBar?
- [x] Fix list item bug where deleting item doesn't update corners
- [x] Add item snapping to horizontal stopwatch laps list
- [x] Fix creating team in tablet mode not selecting the item
- [x] Add a no content hint in the scout template editor
- [x] Navigation drawer
  - The scout template editor will go there since it's really important
  - Basically all the existing menu items can be moved to the navigation drawer
  - Add export all teams button for quick access
  - Make the SnackBar that pops up to let the user select all teams only show up between selecting the second and fifth item so that there are only three occurrences since it was mostly intended to make exporting all teams easier.
      - **Better idea:** make the SnackBar indefinite and cancel it whenever the user starts removing items from their list
  - I don't know how hard this would be, but I could also possibly add a Google style account switcher. **Edit:** not worth it.
- [x] Update the start/stop button for the stopwatch to feel like RS instead of being the gross grey thing it is right now
  - The `Start` part of the button will be filled<sup>[1](#play-filled-button)</sup> to indicate a primary action
  - The `Stop (xx:xx)` part of the button will be outlined<sup>[2](#play-outlined-button)</sup> to indicate a secondary action and **improve clarity for when the timer is actually running**
  - http://stackoverflow.com/a/26686433/4548500
  - http://stackoverflow.com/a/7690648/4548500
  - http://stackoverflow.com/a/33848072/4548500
  - [x] Animate the transition from the two different states
    - https://github.com/nickbutcher/plaid/blob/a6a9ade8658fbd7cf34e2b9aca1e2b908112c86a/app/src/main/java/io/plaidapp/ui/PlayerActivity.java#L332
  - [x] Animate stopwatch icon transition. **Edit:** That's going to be too much of a pain for the little amount of gain.
    - https://github.com/nickbutcher/plaid/blob/a6a9ade8658fbd7cf34e2b9aca1e2b908112c86a/app/src/main/java/io/plaidapp/ui/PlayerActivity.java#L334
    - https://github.com/nickbutcher/plaid/blob/a6a9ade8658fbd7cf34e2b9aca1e2b908112c86a/app/src/main/res/layout/activity_dribbble_player.xml#L81
- [x] The scout template editor should be its own activity
  - The ugly grey delete stuff buttons at the top will be converted to menu items where they are truly out of the way
- [x] Make the text metric be a `TextInputLayout` with pretty app compat colors and animations while keeping the template editor one as is i.e. the metric name will be the hint.
- [x] The `+`/`-` button for the counter will also be filled<sup>[1](#play-filled-button)</sup> buttons
- [x] Fix checkbox metric alignment; it's a little bit too far forward
- [x] The scouts could take on a card UI<sup>[3](#card-look)</sup> depending on how that looks
  - Building on top of #114, each header/subsection group of metrics could be its own card for increased clarity
- [x] Make dialogs look like Plaid<sup>[4](#plaid-dialog)</sup>
- [x] The main team list should also probably take on some sort of Inbox/Google Play style card UI<sup>[6](#card-look-main)</sup>
- [x] Figure out if it's possible to animate the transition from tapping a list item to getting to the Scout activity
  - No, it's not. 😢 
  - http://stackoverflow.com/q/43647375/4548500
- [x] Revamp icons: https://romannurik.github.io/AndroidAssetStudio/index.html

### <a name="play-filled-button">Filled button to indicate primary action</a>
![image](https://cloud.githubusercontent.com/assets/9490724/25367437/8b703998-292a-11e7-9e38-ea00acc3aa3c.png)

### <a name="play-outlined-button">Outlined button to indicate secondary action</a>
![image](https://cloud.githubusercontent.com/assets/9490724/25367489/c914a270-292a-11e7-946d-102a8b0727a8.png)

### <a name="card-look">Card UI look and feel (swipe)</a>
![screenshot_20170424-202011](https://cloud.githubusercontent.com/assets/9490724/25367597/809b0a9c-292b-11e7-9ec4-047dda90b8b8.png)

### <a name="card-look-main">Card UI look and feel</a>
![screenshot_20170426-233907](https://cloud.githubusercontent.com/assets/9490724/25510856/fad0acb0-2b77-11e7-9594-0d7919c76b57.png)

### <a name="plaid-dialog">Plaid dialog</a>
![screenshot_20170429-115727](https://cloud.githubusercontent.com/assets/9490724/25558763/4a3f75ea-2ce2-11e7-802c-218c88fb12ea.png)

### <a name="plaid-player-activity">Plaid player activity</a>
![screenshot_20170429-120823](https://cloud.githubusercontent.com/assets/9490724/25558747/d39f4514-2ce1-11e7-93e5-e52d27654f71.png)

### <a name="possible-add-metric-ui">Possible add metric UI</a>
![screenshot_20170803-210421](https://user-images.githubusercontent.com/9490724/28998838-937c82da-79e9-11e7-9a80-a207a39eb91b.png)

### <a name="chat-bubble-hint">Google chat bubble hint</a>
![screenshot_20170813-195903](https://user-images.githubusercontent.com/9490724/29256847-36fed97a-8062-11e7-957f-48bfd8f607e3.png)

**Comment by SUPERCILEX** [comment]
All left over work has been moved to new issues.
