### ISSUE TITLE
Google I/O 2017 TODO list

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#119]
- [x] Run layout inspector
- [x] https://developers.google.com/actions/
  - Maybe something like "Export my teams"?
- [x] Random idea: it would be cool to be able to automatically detect a set of robot features (e.g. auto pit scout) using Google's new mobile machine learning stuff
- [x] Figure out Google Play app signing
- [x] https://developer.android.com/preview/features/emoji-compat.html
- [x] https://developer.android.com/preview/api-overview.html#notifications
- [x] https://developer.android.com/preview/api-overview.html#category
- [x] https://developer.android.com/preview/api-overview.html#smsh
- [x] https://github.com/SUPERCILEX/Robot-Scouter/blob/master/quality/lint-baseline.xml#L4-L17 can be removed in the new Gradle plugin
- [x] https://developer.android.com/preview/api-overview.html#fvbi-signature
- [x] https://developer.android.com/preview/features/wifi-aware.html
- [x] https://androidstudio.googleblog.com/2017/05/constraintlayout-110-beta-1-release.html
- [x] https://developer.android.com/topic/billions/index.html
- [x] https://developers.google.com/android/guides/releases
- [x] https://developer.android.com/studio/preview/features/index.html#googles_maven_repository
- [x] https://developer.android.com/studio/preview/features/index.html#instant_apps_support
- [x] https://developer.android.com/studio/preview/features/java8-support.html#supported_features
- [x] https://developer.android.com/studio/preview/features/new-android-plugin.html
- [x] Look at all available support libraries
- [x] https://developer.android.com/topic/libraries/architecture/index.html
- [x] https://android-developers.googleblog.com/2017/05/android-and-architecture.html
- [x] https://medium.com/@ianhlake/lifecycle-aware-data-loading-with-android-architecture-components-f95484159de4
- [x] https://developer.android.com/topic/instant-apps/index.html
- [x] Convert constraint layout `right`/`left` attributes to `start`/`end`
- [x] https://developer.android.com/preview/api-overview.html#ulmp
- [x] https://kotlinlang.org/docs/tutorials/koans.html
- [x] https://developer.android.com/kotlin/index.html
- [x] https://firebase.google.com/docs/perf-mon/
- [x] https://developer.android.com/studio/build/dependencies.html#google-maven

![image](https://cloud.githubusercontent.com/assets/9490724/26272566/323d435c-3cd0-11e7-962f-bd3b152f2d69.png)
