### ISSUE TITLE
TODO list for Auth

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#136]
- [x] Add support in settings (#131) to link with another account (which would enable linking a phone account to an email account)
- [x] Upgrade FirebaseUI to support Android O (https://github.com/firebase/FirebaseUI-Android/pull/849 and https://github.com/firebase/FirebaseUI-Android/pull/850)
- [x] Add anonymous auth support to phone auth and make sure stuff is working (https://github.com/firebase/FirebaseUI-Android/pull/309)
- [x] Fix name and photo url being null when linking accounts. Turns out it's expected behaviror:
> Hi Alexandre,
>
>Hope you're having a great day. I appreciate your time and effort on voicing this out.
>
>I have talked to our engineer and he confirmed that this is an intended behavior. A good explanation for that is, if the user_id already exists in Firebase Auth, user attributes from Identity Provider (Google, Facebook etc.) are not populated as top level attributes. Instead, they are updated in sub-level user.providerUserInfo.
>
>Let me know if you have any other Firebase-related issues/questions. Thank you for using Firebase and I wish you all the best in your project. :)
>
>Cheers,
>Hazel
- [x] Fix providers name in `AuthMethodPickerActivity` sometimes collapsing when they shouldn't (https://github.com/firebase/FirebaseUI-Android/pull/711#issuecomment-308880833)
- [x] https://github.com/firebase/FirebaseUI-Android/pull/711
- [x] Add support for GitHub (https://github.com/firebase/FirebaseUI-Android/pull/710). **Edit:** Nah, it's going to be a pain and it's not the priority.
