### ISSUE TITLE
Robot Scouter v2.0 launch checklist

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#147]
- Fix bugs found in QA:
  - [x] **Edit:** not my fault, see https://issuetracker.google.com/issues/68886214. Fix weird collapsing toolbar behavior.
  - [x] Fix tabs being scrolled to incorrectly when there are lots of them
  - [x] Fix FAB staying gone when user signs out
  - [x] Fix metric list flashing after `onStop`/`onStart`, are we not caching it correctly?
  - [x] Deleting metrics in template editor is broken if user used the "Undo" button with an edited value
  - [x] Fix generated file numbers not working with 2+ template files. Ex: `[NAME]...` -> `[NAME_(1)]...` -> `[NAME_(1)]...(1)` instead of `[NAME_(2)]...`
  - [x] Fix export notifications being broken randomly
  - [x] Fix FAM not showing always becoming visible when scrolling up and list is just the right screen size
  - [x] Fix moving first metric in editor auto scrolling to it for some reason  
  - [x] Fix incorrect checkbox name edittext wrapping, multi line is cut off
  - [x] Fix testing using incorrect signing key on private dev branch (upload -> release)
  - [x] Fix background for clicking FAM being white in night mode
  - [x] Fix debug info not getting correct version code. Seems like the constant is begin compiled in before we update it, maybe reflection will help?
  - [x] Fix first scout in new team or template not loading for some reason
- [ ] Fix security rules
- [x] Upgrade to latest Play Billing library
- [x] Pull out Apache POI into separate repo published on JitPack
- [x] Fix MTTP upgrade crash so we can get the latest version
- [x] Do a full performance monitoring session with the new Android studio monitors to try and see what else I can improve
- [x] Look for library updates
- [x] Update Play Store graphics
- [x] Update demo video and GIF
- [x] Write release notes
- [x] Add migrations
  - Make old DB read only and wipe it eventually
  - Migrate local prefs to db prefs
  - Clear cache and data dir
  - Sign everybody out since we're going to be rewriting that stuff and there were sign-in bugs
- [x] Add Firebase perf traces to stuff we want to monitor
- [x] Go through TODOs
- [x] Fix outstanding crash reports
- [x] Go through all suppressed checks
  - `tools:ignore`
  - `@Suppress...`
  - `NOPMD`
  - `ktlint-disable`
  - `//noinpsection`
  - Also do a full Intellij code inspect
- [x] Add `unsafeLazy` function to improve performance: https://proandroiddev.com/kotlin-faster-lazy-for-android-7328ec8d8d57
  - **Better solution:** let's just use KotterKnife https://github.com/JakeWharton/kotterknife
- [x] Rename all strings (they're super messy right now)
  - Prefix each string with the UI screen it's in
- [x] Reorganize [colors](#colors)
- [x] Add item in settings and README to ask people to help [translate RS](https://www.transifex.com/supercilex/robot-scouter/content/)
- [x] For some reason, it looks like proguard isn't going through its optimization step. Figure out why and fix it. https://issuetracker.google.com/issues/64177053

### <a name="colors">Color organizing technique</a>

![screenshot_20170913-210627](https://user-images.githubusercontent.com/9490724/30412090-05161a1a-98ca-11e7-8b8f-baf5fc865018.png)

**Comment by SUPERCILEX** [comment]
Fixed in 2661a1b78a2fccc8ee8336477d8343246b88ac3c
