### ISSUE TITLE
3.0 release checklist

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#244]
### Docs

- [x] Update YT video and GIF
- [x] Update translations
- [x] Add release notes
- [x] Screenshots: https://www.appstorescreenshot.com/
- [x] Hide Auto Scout behind a feature flag
- [x] Update feature list
  - [x] Reorganize features with headers instead of a ton of bullets

### Bugs

- [x] Teams are selected when opening details https://issuetracker.google.com/issues/112106493
- [x] Tapping on the last selected team unselects it but also unexpectedly opens the team
- [x] Report MTTP bug where prompt doesn't update if target view position changed (see https://github.com/sjwall/MaterialTapTargetPrompt/issues/152)
- [x] Rotating screen while in non-teams fragment loses selected teams
- [x] Crash on config change when template editor gets removed
- [x] Item selector is unusable with very small horizontal space
- [x] Figure out `adjustPan` in scout editor and possibly set it dynamically for tablets
- [x] Figure out bottom nav dark mode
- [x] Blank screen opening template on cold app start
- [x] Tablet template editor padding is wrong
- [x] Crash saving scout editor state
- [x] Opening scout editor from link is broken
- [x] Integrated scout editor doesn't work with `fitsInSystemWindow`
- [x] Make toolbar appear when selecting teams
- [x] Crash using exports module for the first time https://issuetracker.google.com/issues/111359204
- [x] Template editor FAB doesn't hide when scrolling
- [x] FAB appears when going to Auto Scout with teams selected
- [x] Teams in tablet mode don't appear selected
- [x] Figure out template `TabLayout` wrong text color
- [x] Report all lint bugs until I can re-enable it

### Maintenance

- [x] https://developer.android.com/guide/topics/text/autofill-optimize#install-autofill-service
- [x] Log notification channel enabled/disabled state
- [x] Check for memory leaks
- [x] Remove or update number formatting (e.g. in `TeamViewHolder`)
- [x] Remove old remote config flags

**Comment by SUPERCILEX** [comment]
Un, no.
