### ISSUE TITLE
Kotlin 1.4 TODO

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#300]
- [ ] Get rid of NewInference compiler flag (it's the default)
- [ ] Run type inference inspection to see if some unnecessary types can be removed
- [ ] Add trailing commas
- [ ] Use `binaries.executable()` in Kotlin/JS
   - ```kotlin
     kotlin {
         js(IR) { // Enable IR backend
             nodejs() // and/or browser()
             binaries.executable()
             moduleName = "myModuleName" // Goes in build/js/packages/myModuleName
         }
     }
     ```
- [ ] Enable API mode with `kotlin.explicitApi()`
