### ISSUE TITLE
TODO random stuff for 1.0.0

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#32]
- [x] http://au.arulnadhan.mobi/docs/
- [x] Go through all of developer.android.com for performance (systrace) and launch checklist and everything https://firebase.google.com/support/guides/launch-checklist
- [x] https://developer.android.com/studio/intro/index.html
- [x] go through dev console
- [x] https://github.com/sterlp/svg2png
- [x] https://github.com/GoogleChrome/custom-tabs-client/blob/master/demos/src/main/java/org/chromium/customtabsdemos/ServiceConnectionActivity.java
- [x] go through google apis and see what I can use (awareness api, nearby api, ...)
- [x] go through todos in code
