### ISSUE TITLE
TODO for official release

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#68]
- [x] Add tablet screenshots
- [x] Make sure outside pull requests don't fail
- [x] Add [link to CLA](https://cla-assistant.io/) in `CONTRIBUTING.md`
- [x] Update outdated play store images (Add images of template editing and 2017 `default-template`)
- [x] Move app to open beta
- [x] Delete all accounts in Firebase
- [x] Close all crashes in Firebase
